name = "edgeaffiliate-ai"
compatibility_date = "2025-06-25"
main = "./Worker.js"

[vars]
AMAZON_US_TAG = "your_temp_tag_us"
AMAZON_SA_TAG = "your_temp_tag_sa"
DEFAULT_GEO = "GLOBAL"

[[kv_namespaces]]
binding = "AFFILIATE_KV"
id = "b6b27e1475174010b3eac796d3bf62b8"
preview_id = "b6b27e1475174010b3eac796d3bf62b8"

[ai]
binding = "AI"
