name = "example-project"
compatibility_date = "2025-06-25"
main = "./Worker.js"

[vars]
AMAZON_US_TAG = "your_tag_here"
AMAZON_SA_TAG = "your_tag_here"
DEFAULT_GEO = "GLOBAL"

# استخدم هذا التنسيق بدلاً من الأقواس المزدوجة
kv_namespaces = [
  {
    binding = "AFFILIATE_KV",
    id = "replace_with_real_id",
    preview_id = "replace_with_preview_id"
  }
]

[ai]
binding = "AI"
